### ISSUE TITLE
"NEM client crashed, sending report..." Namespaces & Subdomains+Mosaics

### ISSUE THREAD

**Issue by fiazk** [NemProject/NEMAndroidApp#242]
It seems there is a bug with multi-sig + Namespaces & Subdomains+Mosaics. I don't really know what happened but now the mob app keeps crashing every time I start it. I was playing with multisig+nanoW+Namespaces & Subdomains+Mosaics. When I went to the mob. app to confirm m-sig tx it just started crashing.

These are the addresses involved:

TBIG2FEVUMVSFCEDUM2OISQED5M2HUD67RYV6ZSE
TABFN75542Z66BPZMRZOP4QDUZRFABE6DNOZ3DIV
TDQUTONAF37FDIET6XXTNZP4O7SZX5LUHXDI3F6T

![photo_2016-08-12_19-38-28](https://cloud.githubusercontent.com/assets/17099341/17631634/29caea4a-60c5-11e6-85ce-2f91b83805ee.jpg)

Mobile: Samsung S3
Android 4.3
NEM 1.0.53

NDAZM2-KCD2XB-4Y7XMM-J5UUZ3-2ZCBHE-MHRHF4-3U3W

**Comment by fiazk** [comment]
@jabo38 @fyahfox an important one imo

**Comment by jabo38** [comment]
@fiazk can you kill the app in the background and restart it. at that point it won't crash anymore when you start.  then can you try to reproduce it.  it is important to know how this happened.

**Comment by fiazk** [comment]
@jabo38 I did so and it keeps crashing. I will PM you the PK so you can see it as well

**Comment by fiazk** [comment]
I have also deleted all the cache and imported the acc again but it keeps crashing. I have sent you my PK and acc name so you can reproduce it on your end @jabo38

**Comment by jabo38** [comment]
address
TBIG2F-EVUMVS-FCEDUM-2OISQE-D5M2HU-D67RYV-6ZSE

private key
449554f1938d39d3e566e1b2c4dc5380e669e9a10405d359f498b0d412ef9e9f

**Comment by am4n0w4r** [comment]
Application doesn't support mosaic transactions

**Comment by fiazk** [comment]
I just crashed another account. However, this time it was by creating a namespace in the nano wallet and involving a mob acc with multi-sig with the namespace tx.

Public Key: ea5a67449d7775061c466e00bb98d12906d7364e75219e1993f56304e904495d
Private Key: 0099d369894162771264ea247a2964332ebf85cfe6785b8a32ea9c90bf07f96a41

**Comment by fiazk** [comment]
To reproduce: 1) Created 1 mob acc and 1 nano wallet acc with 2 addresses (I guess it could be also only 1 address). 2) Turned one nano wallet address into multi-sig by making the other 2 addresses cosigners (1 from NW and 1 from mob app). 3) Created a namespace with the multi-sig acc

**Comment by jabo38** [comment]
@am4n0w4r what basically is going on is he was working on Nano wallet doing regular NEM transactions and had the same account on his phone.  But now the app is broken.  So even though the phone app doesn't do mosaic/namespace transactions, it still needs to not break when they are done elsewhere.  I loaded his key into my app and when I did the account wouldn't work.

**Comment by am4n0w4r** [comment]
Please test in 1.0.61 testnet, this should be fixed, right now I don't have possibility to create mosaics, cannot test it myself

**Comment by fiazk** [comment]
Still crashing. I started with a brand new acc Private Key: 126182ede6e58c9285922aaee792c7695540cc97eea27c4ec168cc468a52c7f9

I also imported the previous compromised account and it also crashes

**Comment by fiazk** [comment]
Sorry I just realised the version I was using is .60 @jabo38 where can I download the .61

**Comment by fiazk** [comment]
@jabo38 the following link gives me 404 error https://drive.google.com/open?id=0B-3myDNfWMs2cElNa3pGenpySHM1

**Comment by am4n0w4r** [comment]
https://drive.google.com/open?id=0B-3myDNfWMs2bC1OSk1HLU5SX1k here is version 61

**Comment by fiazk** [comment]
@am4n0w4r This is mainnet, could you please share 61 for testnet. Thanks

**Comment by kmiliak** [comment]
@fiazk   testnet https://drive.google.com/file/d/0B-3myDNfWMs2bC1OSk1HLU5SX1k/view?usp=sharing

**Comment by fiazk** [comment]
@kmiliak Thanks

**Comment by fiazk** [comment]
Now I get the notification (didn't happen before) but once I click "Show" the app crashes
![photo_2016-09-01_18-57-01](https://cloud.githubusercontent.com/assets/17099341/18176456/fafd9472-7075-11e6-8bb6-8b096fdd80af.jpg)

**Comment by am4n0w4r** [comment]
Please test again in testnet 1.0.62;

**Comment by fiazk** [comment]
link please?

**Comment by jabo38** [comment]
Here is link to Android new testnet release
https://drive.google.com/file/d/0B-3myDNfWMs2NHhGMVl6UVB6SU0/view?usp=sharing

and Mainnet:

https://drive.google.com/file/d/0B-3myDNfWMs2eDFtYkxqT1U2RnM/view?usp=sharing

Please make the fresh install.

**Comment by fiazk** [comment]
Good news, it is fixed.

**Comment by am4n0w4r** [comment]
@fiazk please close the issue if it's fixed.

**Comment by jabo38** [comment]
Bounty Paid Tx Hash: 746fa3bc1299626fe07fb74b2b8a5430d0755ed2f436ac25605caa3cd9ec6ade
--
